### ISSUE TITLE
 Is there a more complete code?

### ISSUE THREAD

**Issue by alice-yi** [Thvnvtos/Lung_Segmentation#1]
Hello, I am also doing the topic of 3D lung segmentation. If you have better results, I want to discuss it.

**Comment by Thvnvtos** [comment]
Hello Alice, at the moment this is all the code there is, I just started the project. My main objective is benchmarking a nodule detection and segmentation model, this is just an intermediary step to get lung masks for a subset of my data.
Feel free to contact me by email if you want to discuss it.
