### ISSUE TITLE
Sharing code to plot segmentation results

### ISSUE THREAD

**Issue by weihao94** [Thvnvtos/Lung_Segmentation#3]
Hi, this is great work! Thanks for sharing this.

Just curious, are you able to provide the code/script(s) used to generate the snippets of the segmentation in your README (https://github.com/Thvnvtos/Lung_Segmentation)?

If you have used a software instead to visualize the results, it'll be great if you could state which software was used too.

Thank you and hope to hear from you.

**Comment by Thvnvtos** [comment]
Hi, thanks for your interest.
I used ITK-snap for the visualization, it's a free software, you just need to save your numpy arrays corresponding to 3D volumes in a compatible format for the software ( like NRRD, or Niftii, ...)

**Comment by weihao94** [comment]
@Thvnvtos Thanks for the prompt reply in these troubling times. Just to clarify, for the file format used as input to ITK-snap, did you use exactly NRRD like in `nrrd.write("mask3D.nrrd", mask[0][0])` at https://github.com/Thvnvtos/Lung_Segmentation/blob/unet3d/eval.py? Reason I'm asking is for reproducibility purposes. I do have just one more question, which I'll create a separate issue in just a bit. Thanks!

**Comment by Thvnvtos** [comment]
Hi, yes I used NRRD, `nrrd.write("mask3D.nrrd", mask[0][0])` mask3D is the lung's mask that, afterwards you can use ITK-Snap to open the 3D scan and add the mask on top of it to reproduce the snippets in the Readme.

**Comment by weihao94** [comment]
@Thvnvtos Excellent, thanks again for the prompt clarifications. I'll be closing this issue now.
