### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by MScDaniel** [Thvnvtos/Lung_Segmentation#7]
Hi there!

First of all, thank you for sharing your code with the rest of us.

I was wondering if you ran into the same issue as I did. The problem I encounter is that when I attempt to train the network I get a RuntimeError. My batch size is 1 and my GPU has got 8GB of memory, which I believe should be enough. Have you had this issue before? And if so, how did you solve it?

The error happens when running train.py and it reaches the following line:

logits = unet(batch)

Thank you for your help!

**Comment by Thvnvtos** [comment]
Hi, 
Yes its normal to have this error, I trained this model using a GPU with 32Gb of memory.
The only approach you can do, is to use a 2D model instead that works on each slice separately and concatenate the result at the end.
And maybe Try Resnet Blocks instead the normal Conv layers that I used in here.
Good Luck.

**Comment by MScDaniel** [comment]
Thank you so much for your quick response! I will try that and also to run the script on a different machine. Thank you again!
